### ISSUE TITLE
IRCCloud Enterprise won't connect after upgrade to 3.0 (crash)

### ISSUE THREAD

**Issue by justdave** [irccloud/android#137] opened 2016-07-02 04:16 UTC
Now using 3.1, didn't fix the problem.

I get push notifications, but when I try to connect to actually read/reply, It says "Connecting" then "Loading" and after the bar gets all the way across, it goes to "Reconnecting in 0:30" and starts counting down.  It then loops like that forever.

Hooking up USB debugging, I see the following stack trace get dumped in the log at the point it switches to "Reconnecting":

```
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at com.irccloud.android.NetworkConnection$9$12.parse(NetworkConnection.java:2123)
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at com.irccloud.android.NetworkConnection.parse_object(NetworkConnection.java:2778)
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at com.irccloud.android.NetworkConnection.access$1300(NetworkConnection.java:121)
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at com.irccloud.android.NetworkConnection$OOBIncludeTask.doInBackground(NetworkConnection.java:3241)
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at com.irccloud.android.NetworkConnection$OOBIncludeTask.doInBackground(NetworkConnection.java:3118)
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
W | 07-02 00:11:19.509 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W | 07-02 00:11:19.510 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W | 07-02 00:11:19.510 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W | 07-02 00:11:19.510 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W | 07-02 00:11:19.510 |  6544 | com.irccloud.android.enterprise               | IRCCloud                  | 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by c99koder** [comment] 2016-07-02 05:01
Hi Dave,

This should be fixed in the next update.  Please switch to the beta channel here and confirm the issue is resolved, so we can push the fix out to everyone: https://play.google.com/apps/testing/com.irccloud.android.enterprise

It may take a few hours for your device to receive the update after opting in to the beta channel.

Thanks,
-Sam

**Comment by justdave** [comment] 2016-07-02 05:29
Opted in to beta, and waiting for it to show up.  Thanks for the quick response!

**Comment by justdave** [comment] 2016-07-02 06:45
ok, beta showed up finally, confirmed fixed, it works. :-)

**Comment by c99koder** [comment] 2016-07-02 15:10
Great! We'll be releasing this update to all users shortly. Thanks for letting us know about the issue.

**Closed by c99koder** 2016-07-02 15:10 UTC
Labels: bug
